import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
import { Loop } from '../core/Loop';
import { createRenderer, resizeRenderer } from '../core/Renderer';

type Category='beds'|'furniture'|'workspace'|'light'|'decor'|'keepsake'|'plant';
type ItemData={id:string;kind:string;name:string;category:Category;x:number;y?:number;z:number;rot:number;color:number;scale?:number;supportId?:string};
type CatalogItem={kind:string;name:string;category:Category;icon:string;note:string};

const CATALOG:CatalogItem[]=[
 {kind:'bed',name:'Patchwork bed',category:'beds',icon:'🛏️',note:'Soft & sleepy'},
 {kind:'canopy',name:'Storybook canopy',category:'beds',icon:'🏰',note:'Curtains at bedtime'},
 {kind:'desk',name:'Writing desk',category:'furniture',icon:'🪵',note:'For little letters'},
 {kind:'chair',name:'Sunday chair',category:'furniture',icon:'🪑',note:'A quiet corner'},
 {kind:'shelf',name:'Memory shelf',category:'furniture',icon:'📚',note:'Treasures live here'},
 {kind:'sofa',name:'Little loveseat',category:'furniture',icon:'🛋️',note:'Room for two'},
 {kind:'wardrobe',name:'Sunday wardrobe',category:'furniture',icon:'🚪',note:'Secret pockets'},
 {kind:'nightstand',name:'Bedside table',category:'furniture',icon:'🗄️',note:'One tiny drawer'},
 {kind:'ottoman',name:'Floor pouffe',category:'furniture',icon:'🧶',note:'Soft woven seat'},
 {kind:'toybox',name:'Old toy chest',category:'furniture',icon:'🧰',note:'Full of possibilities'},
 {kind:'dresser',name:'Mirror dresser',category:'furniture',icon:'🪞',note:'Morning light'},
 {kind:'birchtable',name:'Light birch table',category:'furniture',icon:'▱',note:'Soft edges, splayed legs'},
 {kind:'sectional',name:'Corner sofa',category:'furniture',icon:'🛋️',note:'Stretch-out seating'},
 {kind:'armchair',name:'Deep armchair',category:'furniture',icon:'💺',note:'A proper reading chair'},
 {kind:'coffeetable',name:'Coffee table',category:'furniture',icon:'▰',note:'Low and useful'},
 {kind:'tallbookcase',name:'Tall bookcase',category:'furniture',icon:'📚',note:'A whole wall of books'},
 {kind:'lowbookcase',name:'Low bookcase',category:'furniture',icon:'📖',note:'Books within reach'},
 {kind:'cubestorage',name:'Cube storage',category:'furniture',icon:'▦',note:'Nine tidy cubbies'},
 {kind:'deskchair',name:'Rolling desk chair',category:'workspace',icon:'🪑',note:'Ready for homework'},
 {kind:'desktop',name:'Desktop computer',category:'workspace',icon:'🖥️',note:'The whole setup'},
 {kind:'monitor',name:'Computer monitor',category:'workspace',icon:'🖥️',note:'A bright little screen'},
 {kind:'laptop',name:'Open laptop',category:'workspace',icon:'💻',note:'Work anywhere'},
 {kind:'keyboard',name:'Keyboard & mouse',category:'workspace',icon:'⌨️',note:'Clickety-clack'},
 {kind:'speakers',name:'Stereo speakers',category:'workspace',icon:'🔊',note:'A pair for the desk'},
 {kind:'printer',name:'Home printer',category:'workspace',icon:'🖨️',note:'Paper included'},
 {kind:'filing',name:'Filing cabinet',category:'workspace',icon:'🗄️',note:'Three neat drawers'},
 {kind:'deskset',name:'Studio desk',category:'workspace',icon:'🖥️',note:'Wide modern workspace'},
 {kind:'lamp',name:'Honey lamp',category:'light',icon:'💡',note:'Warm evening glow'},
 {kind:'fairy',name:'Fairy lights',category:'light',icon:'✨',note:'Tiny constellations'},
 {kind:'lantern',name:'Paper lantern',category:'light',icon:'🏮',note:'A peachy glow'},
 {kind:'candles',name:'Candle trio',category:'light',icon:'🕯️',note:'Three warm wishes'},
 {kind:'lavalamp',name:'Dreamy lava lamp',category:'light',icon:'🫧',note:'Slow color clouds'},
 {kind:'teddy',name:'Old teddy',category:'keepsake',icon:'🧸',note:'A faithful friend'},
 {kind:'radio',name:'Pocket radio',category:'keepsake',icon:'📻',note:'Songs after school'},
 {kind:'train',name:'Wooden train',category:'keepsake',icon:'🚂',note:'Still runs on dreams'},
 {kind:'books',name:'Story books',category:'keepsake',icon:'📚',note:'Dog-eared favorites'},
 {kind:'camera',name:'Holiday camera',category:'keepsake',icon:'📷',note:'Keep this moment'},
 {kind:'record',name:'Record player',category:'keepsake',icon:'💿',note:'Songs on vinyl'},
 {kind:'musicbox',name:'Music box',category:'keepsake',icon:'🎵',note:'Turn the little key'},
 {kind:'snowglobe',name:'Snow globe',category:'keepsake',icon:'🔮',note:'A world inside'},
 {kind:'globe',name:'Schoolroom globe',category:'keepsake',icon:'🌍',note:'Anywhere from here'},
 {kind:'dollhouse',name:'Tiny dollhouse',category:'keepsake',icon:'🏠',note:'A room within a room'},
 {kind:'plant',name:'Window fern',category:'plant',icon:'🌿',note:'Something growing'},
 {kind:'flowers',name:'Jam-jar flowers',category:'plant',icon:'🌼',note:'From the garden'},
 {kind:'cactus',name:'Button cactus',category:'plant',icon:'🌵',note:'Small but brave'},
 {kind:'monstera',name:'Big-leaf plant',category:'plant',icon:'🍃',note:'A leafy friend'},
 {kind:'mushroom',name:'Mushroom pot',category:'plant',icon:'🍄',note:'Forest-floor magic'},
 {kind:'roundrug',name:'Round braided rug',category:'decor',icon:'🟠',note:'A cozy little island'},
 {kind:'mirror',name:'Standing mirror',category:'decor',icon:'🪞',note:'Catch the window light'},
 {kind:'clock',name:'Mantel clock',category:'decor',icon:'🕰️',note:'Slow afternoons'},
 {kind:'basket',name:'Woven basket',category:'decor',icon:'🧺',note:'For odds and ends'},
 {kind:'cushion',name:'Patchwork cushion',category:'decor',icon:'🟥',note:'One more soft thing'},
];
const PALETTE=[0xb75e4b,0x6f8875,0xd7a34c,0x66858d,0xd8a69a,0x8b6048];
const SUPPORT_KINDS=new Set(['bed','canopy','sofa','sectional','chair','armchair','desk','deskset','birchtable','coffeetable','nightstand','dresser','filing','toybox','shelf','tallbookcase','lowbookcase','cubestorage']);
const SUPPORT_HEIGHTS:Record<string,number>={bed:1.29,canopy:1.1,sofa:1.2,sectional:1.14,chair:1.2,armchair:1.25,desk:1.9,deskset:1.82,birchtable:1.95,coffeetable:.88,nightstand:1.48,dresser:1.86,filing:1.72,toybox:1.34,shelf:2.24,tallbookcase:4.25,lowbookcase:1.75,cubestorage:2.55};
const FLOOR_ONLY_KINDS=new Set(['bed','canopy','desk','deskset','birchtable','chair','deskchair','armchair','shelf','sofa','sectional','wardrobe','nightstand','ottoman','toybox','dresser','filing','coffeetable','tallbookcase','lowbookcase','cubestorage','roundrug','mirror']);

export class Game{
 private renderer:THREE.WebGLRenderer; private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(36,1,.1,100); private controls:OrbitControls;
 private loop=new Loop((d,e)=>this.update(d,e),()=>this.renderer.render(this.scene,this.camera)); private ray=new THREE.Raycaster(); private pointer=new THREE.Vector2();
 private items=new Map<string,THREE.Group>(); private data:ItemData[]=[]; private selected?:THREE.Group; private drag=false; private dragOffset=new THREE.Vector3(); private dragHeight=0; private history:ItemData[][]=[]; private future:ItemData[][]=[]; private touches=new Map<number,PointerEvent>(); private pinchStart=0; private pinchScale=1;
 private floorTex?:THREE.Texture; private evening=false; private keyLight?:THREE.SpotLight; private lampLight?:THREE.PointLight; private dust?:THREE.Points; private saveTimer=0; private ambience=new Audio(`${import.meta.env.BASE_URL}assets/audio/room-memory-loop.mp3`);
 constructor(private canvas:HTMLCanvasElement){this.renderer=createRenderer(canvas);this.renderer.toneMappingExposure=1.12;this.camera.position.set(12,10,15);this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(0,2.3,0);this.controls.enableDamping=true;this.controls.minDistance=10;this.controls.maxDistance=28;this.controls.maxPolarAngle=Math.PI*.48;this.controls.minPolarAngle=.45;this.createWorld();this.bindUI();this.bindTouchExtras();this.load();resizeRenderer(this.renderer,this.camera,1.7);this.publish()}
 start(){this.loop.start()} dispose(){this.loop.stop();this.controls.dispose();this.renderer.dispose();clearTimeout(this.saveTimer)}
 private createWorld(){this.scene.background=new THREE.Color(0x9fa9a1);this.scene.fog=new THREE.Fog(0xb9b4a5,24,46);const hemi=new THREE.HemisphereLight(0xc9dddf,0x5b382b,1.9);this.scene.add(hemi);this.keyLight=new THREE.SpotLight(0xffd69b,80,35,.65,.5,1.3);this.keyLight.position.set(-5,10,6);this.keyLight.target.position.set(0,0,0);this.keyLight.castShadow=true;this.keyLight.shadow.mapSize.set(1024,1024);this.scene.add(this.keyLight,this.keyLight.target);const fill=new THREE.DirectionalLight(0xaed7e6,1.6);fill.position.set(8,7,-4);this.scene.add(fill);this.lampLight=new THREE.PointLight(0xffa94e,5,10,2);this.lampLight.position.set(-4,4,-3);this.scene.add(this.lampLight);
 const room=new THREE.Group();const floorMat=new THREE.MeshStandardMaterial({color:0x8d6548,roughness:.72});const floor=new THREE.Mesh(new THREE.BoxGeometry(14,.28,11),floorMat);floor.receiveShadow=true;floor.position.y=-.15;room.add(floor);for(let i=-6;i<=6;i++){const seam=new THREE.Mesh(new THREE.BoxGeometry(.025,.01,10.8),new THREE.MeshBasicMaterial({color:0x5e4435,transparent:true,opacity:.32}));seam.position.set(i,0.005,0);room.add(seam)}const wallMat=new THREE.MeshStandardMaterial({color:0xe8d7b8,roughness:.92});const back=new THREE.Mesh(new THREE.BoxGeometry(14,7,.18),wallMat);back.position.set(0,3.5,-5.45);back.receiveShadow=true;room.add(back);const side=new THREE.Mesh(new THREE.BoxGeometry(.18,7,11),wallMat);side.position.set(-6.9,3.5,0);side.receiveShadow=true;room.add(side);const baseMat=new THREE.MeshStandardMaterial({color:0xf2e5cf,roughness:.7});const base1=new THREE.Mesh(new THREE.BoxGeometry(14,.32,.22),baseMat);base1.position.set(0,.18,-5.3);room.add(base1);const base2=new THREE.Mesh(new THREE.BoxGeometry(.22,.32,11),baseMat);base2.position.set(-6.75,.18,0);room.add(base2);this.addWindow(room);this.addBuiltIns(room);this.scene.add(room);this.addRug();this.addDust();}
 private addWindow(room:THREE.Group){const frameMat=new THREE.MeshStandardMaterial({color:0xf3e8d1,roughness:.55});const glass=new THREE.Mesh(new THREE.PlaneGeometry(4.2,3),new THREE.MeshBasicMaterial({color:0xa9d5dc}));glass.position.set(2.4,4,-5.34);room.add(glass);for(const [x,y,w,h] of [[2.4,5.55,4.7,.18],[2.4,2.45,4.7,.18],[.05+0,4,.18,3.3],[4.75,4,.18,3.3],[2.4,4,.14,3.1],[2.4,4,4.4,.12]] as number[][]){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,.18),frameMat);m.position.set(x,y,-5.18);room.add(m)}const curtainMat=new THREE.MeshStandardMaterial({color:0xc98270,roughness:1,side:THREE.DoubleSide});for(const x of [-.35,5.15]){const c=new THREE.Mesh(new THREE.PlaneGeometry(1.1,3.8,6,8),curtainMat);c.position.set(x,4,-5.05);c.rotation.y=x<0?.18:-.18;room.add(c)}}
 private addBuiltIns(room:THREE.Group){const wood=new THREE.MeshStandardMaterial({color:0x6f4935,roughness:.62});const shelf=new THREE.Mesh(new THREE.BoxGeometry(3,.18,.75),wood);shelf.position.set(-4.7,4.3,-5);shelf.castShadow=true;room.add(shelf);for(let i=0;i<4;i++){const book=new THREE.Mesh(new THREE.BoxGeometry(.28,.7,.55),new THREE.MeshStandardMaterial({color:PALETTE[i],roughness:.85}));book.position.set(-5.5+i*.35,4.75,-5);book.rotation.z=(i-1.5)*.04;room.add(book)}const posters=[0xd19b78,0x78928b,0xd7b363];posters.forEach((c,i)=>{const frame=new THREE.Mesh(new THREE.BoxGeometry(1.25,1.55,.08),wood);frame.position.set(-6.72,3.3+i*1.25,2.6-i*1.35);frame.rotation.y=Math.PI/2;room.add(frame);const art=new THREE.Mesh(new THREE.PlaneGeometry(1.05,1.35),new THREE.MeshBasicMaterial({color:c}));art.position.set(-6.66,3.3+i*1.25,2.6-i*1.35);art.rotation.y=Math.PI/2;room.add(art)})}
 private addRug(){this.floorTex=new THREE.TextureLoader().load(`${import.meta.env.BASE_URL}assets/rug-memory.png`);this.floorTex.colorSpace=THREE.SRGBColorSpace;const rug=new THREE.Mesh(new THREE.PlaneGeometry(7.6,5.8),new THREE.MeshStandardMaterial({map:this.floorTex,roughness:1}));rug.rotation.x=-Math.PI/2;rug.position.set(.6,.025,.5);rug.receiveShadow=true;this.scene.add(rug)}
 private addDust(){const geo=new THREE.BufferGeometry();const p=[];for(let i=0;i<110;i++)p.push((Math.random()-.5)*13,Math.random()*6,(Math.random()-.5)*10);geo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));this.dust=new THREE.Points(geo,new THREE.PointsMaterial({color:0xffe2a8,size:.035,transparent:true,opacity:.5}));this.scene.add(this.dust)}
 private bindUI(){const $=(s:string)=>document.querySelector<HTMLElement>(s)!;$('#begin').onclick=()=>{$('#welcome').classList.add('gone');this.audio('begin')};$('#open-catalog').onclick=()=>$('#catalog').classList.remove('closed');$('#close-catalog').onclick=()=>$('#catalog').classList.add('closed');$('#reset-view').onclick=()=>this.resetCamera();$('#time-toggle').onclick=()=>this.toggleTime();$('#undo').onclick=()=>this.undo();$('#redo').onclick=()=>this.redo();$('#rotate-left').onclick=()=>this.modify(-Math.PI/12);$('#rotate-right').onclick=()=>this.modify(Math.PI/12);$('#lower').onclick=()=>this.adjustHeight(-.2);$('#raise').onclick=()=>this.adjustHeight(.2);$('#color').onclick=()=>this.recolor();$('#duplicate').onclick=()=>this.duplicate();$('#remove').onclick=()=>this.remove();$('#sound').onclick=()=>this.audio('chime');document.querySelectorAll<HTMLButtonElement>('#categories button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#categories button').forEach(x=>x.classList.remove('active'));b.classList.add('active');this.renderCatalog((b.dataset.cat||'all') as Category|'all')});this.renderCatalog('all');this.canvas.addEventListener('pointerdown',e=>this.pointerDown(e));this.canvas.addEventListener('pointermove',e=>this.pointerMove(e));window.addEventListener('pointerup',()=>this.pointerUp());window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo()}else if(e.key==='Delete'||e.key==='Backspace')this.remove();else if(e.key.toLowerCase()==='q')this.modify(-Math.PI/12);else if(e.key.toLowerCase()==='e')this.modify(Math.PI/12);else if(e.key.toLowerCase()==='r')this.adjustHeight(.2);else if(e.key.toLowerCase()==='f')this.adjustHeight(-.2);else if(e.key==='Escape')this.select(undefined)})}
 private bindTouchExtras(){document.querySelector('#smaller')?.addEventListener('click',()=>this.resizeSelected(-.1));document.querySelector('#larger')?.addEventListener('click',()=>this.resizeSelected(.1));const distance=()=>{const p=[...this.touches.values()];return p.length<2?0:Math.hypot(p[0].clientX-p[1].clientX,p[0].clientY-p[1].clientY)};this.canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch')return;this.touches.set(e.pointerId,e);if(this.touches.size===2&&this.selected){if(this.drag)this.pointerUp();this.checkpoint();this.pinchStart=distance();this.pinchScale=this.findData()?.scale??1;this.controls.enabled=false;e.stopImmediatePropagation();return}this.setPointer(e);this.ray.setFromCamera(this.pointer,this.camera);if(this.ray.intersectObjects([...this.items.values()],true).length){this.pointerDown(e);e.stopImmediatePropagation()}},true);this.canvas.addEventListener('pointermove',e=>{if(e.pointerType!=='touch')return;this.touches.set(e.pointerId,e);if(this.pinchStart&&this.selected){const d=this.findData();if(d){d.scale=THREE.MathUtils.clamp(this.pinchScale*distance()/this.pinchStart,.55,1.6);this.selected.scale.setScalar(d.scale)}e.stopImmediatePropagation()}else if(this.drag){this.pointerMove(e);e.stopImmediatePropagation()}},true);const finish=(e:PointerEvent)=>{this.touches.delete(e.pointerId);if(this.pinchStart){this.pinchStart=0;this.controls.enabled=true;this.changed()}else this.pointerUp()};window.addEventListener('pointerup',finish,true);window.addEventListener('pointercancel',finish,true);this.canvas.addEventListener('lostpointercapture',finish);window.addEventListener('blur',()=>{this.touches.clear();this.pinchStart=0;this.pointerUp();this.controls.enabled=true});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.touches.clear();this.pinchStart=0;this.pointerUp();this.controls.enabled=true}})}
 private renderCatalog(cat:Category|'all'){const host=document.querySelector('#items')!;host.innerHTML='';CATALOG.filter(x=>cat==='all'||x.category===cat).forEach(x=>{const b=document.createElement('button');b.className='item';b.innerHTML=`<span>${x.icon}</span>${x.name}<small>${x.note}</small>`;b.onclick=()=>{this.add(x);if(innerWidth<700)document.querySelector('#catalog')?.classList.add('closed')};host.appendChild(b)})}
 private add(c:CatalogItem,d?:Partial<ItemData>,record=true){if(record)this.checkpoint();const data:ItemData={id:d?.id||crypto.randomUUID(),kind:c.kind,name:c.name,category:c.category,x:d?.x??0,y:d?.y??0,z:d?.z??1,rot:d?.rot||0,color:d?.color??PALETTE[Math.floor(Math.random()*PALETTE.length)],scale:d?.scale??1,supportId:d?.supportId};const g=this.makeItem(data);if(d?.x===undefined&&d?.z===undefined){const spot=this.findOpenFloorSpot(g);data.x=spot.x;data.z=spot.z;g.position.set(data.x,data.y??0,data.z)}this.data.push(data);this.items.set(data.id,g);this.scene.add(g);this.select(g);if(record){this.audio('place');this.changed()}return g}
 private findOpenFloorSpot(g:THREE.Group){const size=new THREE.Box3().setFromObject(g).getSize(new THREE.Vector3());const halfX=Math.max(.35,size.x/2),halfZ=Math.max(.35,size.z/2),padding=.28;const minX=-5.7+halfX,maxX=5.7-halfX,minZ=-4.5+halfZ,maxZ=4.5-halfZ;const occupied=[...this.items.values()].map(item=>new THREE.Box3().setFromObject(item));const candidates:THREE.Vector2[]=[];for(let ring=0;ring<7;ring++){const radius=ring*1.25;const count=ring===0?1:ring*10;for(let i=0;i<count;i++){const angle=-Math.PI/4+i*Math.PI*2/count;candidates.push(new THREE.Vector2(Math.cos(angle)*radius,1+Math.sin(angle)*radius))}}let best=new THREE.Vector2(THREE.MathUtils.clamp(0,minX,maxX),THREE.MathUtils.clamp(1,minZ,maxZ)),bestOverlap=Infinity;for(const p of candidates){p.x=THREE.MathUtils.clamp(p.x,minX,maxX);p.y=THREE.MathUtils.clamp(p.y,minZ,maxZ);let overlap=0;for(const box of occupied){const dx=Math.min(p.x+halfX+padding,box.max.x)-Math.max(p.x-halfX-padding,box.min.x);const dz=Math.min(p.y+halfZ+padding,box.max.z)-Math.max(p.y-halfZ-padding,box.min.z);if(dx>0&&dz>0)overlap+=dx*dz}if(overlap===0)return{x:p.x,z:p.y};if(overlap<bestOverlap){bestOverlap=overlap;best.copy(p)}}return{x:best.x,z:best.y}}
 private makeItem(d:ItemData){const g=new THREE.Group();g.userData.itemId=d.id;g.name=d.name;const mat=new THREE.MeshStandardMaterial({color:d.color,roughness:.72});const cream=new THREE.MeshStandardMaterial({color:0xf1dfc1,roughness:.9});const dark=new THREE.MeshStandardMaterial({color:0x5a392b,roughness:.58});const add=(geo:THREE.BufferGeometry,m:THREE.Material,x:number,y:number,z:number,rx=0,ry=0,rz=0)=>{const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.rotation.set(rx,ry,rz);o.castShadow=true;o.receiveShadow=true;g.add(o);return o};
 if(d.kind==='bed'){add(new THREE.BoxGeometry(3,.55,4),dark,0,.45,0);add(new THREE.BoxGeometry(2.8,.45,3.65),cream,0,.95,.08);add(new THREE.BoxGeometry(2.72,.08,2.28),mat,0,1.22,.66);add(new THREE.BoxGeometry(1.12,.22,.62),cream,-.62,1.34,-1.08);add(new THREE.BoxGeometry(1.12,.22,.62),cream,.62,1.34,-1.08);}
 else if(d.kind==='desk'){add(new THREE.BoxGeometry(2.8,.22,1.4),mat,0,1.75,0);for(const x of [-1.15,1.15])for(const z of [-.5,.5])add(new THREE.CylinderGeometry(.11,.14,1.65,8),dark,x,.85,z);add(new THREE.BoxGeometry(1.2,.1,.85),cream,-.35,1.92,0,.0,0,-.08)}
 else if(d.kind==='birchtable'){const birch=new THREE.MeshStandardMaterial({color:0xe8c99c,roughness:.68,metalness:0});const grain=new THREE.MeshBasicMaterial({color:0xcda97b,transparent:true,opacity:.18});add(new RoundedBoxGeometry(3.8,.18,2.2,4,.12),birch,0,1.86,0);add(new THREE.BoxGeometry(3.35,.25,.12),birch,0,1.68,.88);add(new THREE.BoxGeometry(3.35,.25,.12),birch,0,1.68,-.88);add(new THREE.BoxGeometry(.12,.25,1.65),birch,1.62,1.68,0);add(new THREE.BoxGeometry(.12,.25,1.65),birch,-1.62,1.68,0);for(const x of [-1.58,1.58])for(const z of [-.74,.74])add(new THREE.CylinderGeometry(.11,.16,1.72,8),birch,x,.86,z,-Math.sign(z)*.085,0,Math.sign(x)*.085);for(let i=0;i<7;i++){const line=add(new THREE.BoxGeometry(3.1-(i%2)*.35,.008,.01+(i%3)*.004),grain,(i%2-.5)*.18,1.956,-.73+i*.23);line.rotation.y=(i%3-1)*.009}}
 else if(d.kind==='chair'){add(new THREE.BoxGeometry(1.4,.25,1.4),mat,0,1.05,0);add(new THREE.BoxGeometry(1.4,1.8,.22),mat,0,1.85,.58,-.1);for(const x of [-.5,.5])for(const z of [-.5,.5])add(new THREE.CylinderGeometry(.1,.13,1,8),dark,x,.5,z)}
 else if(d.kind==='shelf'){for(let i=0;i<3;i++)add(new THREE.BoxGeometry(2.5,.18,.8),mat,0,.45+i*.8,0);for(const x of [-1.1,1.1])add(new THREE.BoxGeometry(.18,2.2,.8),dark,x,1.25,0)}
 else if(d.kind==='lamp'){add(new THREE.CylinderGeometry(.5,.65,.18,20),dark,0,.1,0);add(new THREE.CylinderGeometry(.07,.09,1.8,10),dark,0,1,0);add(new THREE.CylinderGeometry(.34,.72,.7,20,1,true),mat,0,2,0);const bulb=add(new THREE.SphereGeometry(.18,16,12),new THREE.MeshBasicMaterial({color:0xffd285}),0,1.88,0);bulb.userData.glow=true}
 else if(d.kind==='fairy'){for(let i=0;i<9;i++){const x=-1.8+i*.45,y=1.5+Math.sin(i*.8)*.25;add(new THREE.SphereGeometry(.08,10,8),new THREE.MeshBasicMaterial({color:PALETTE[i%PALETTE.length],toneMapped:false}),x,y,0)} }
 else if(d.kind==='teddy'){add(new THREE.SphereGeometry(.55,18,14),mat,0,.7,0);add(new THREE.SphereGeometry(.42,18,14),mat,0,1.45,0);for(const x of [-.34,.34])add(new THREE.SphereGeometry(.18,14,10),mat,x,1.75,0);for(const x of [-.25,.25])add(new THREE.SphereGeometry(.045,8,6),dark,x,1.52,.38)}
 else if(d.kind==='radio'){add(new THREE.BoxGeometry(1.5,.9,.55),mat,0,.55,0);add(new THREE.CircleGeometry(.28,20),dark,-.32,.58,.281);add(new THREE.CylinderGeometry(.08,.08,.25,10),cream,.45,.72,.32,Math.PI/2);add(new THREE.CylinderGeometry(.08,.08,.25,10),cream,.45,.42,.32,Math.PI/2)}
 else if(d.kind==='train'){add(new THREE.BoxGeometry(1.5,.5,.65),mat,0,.48,0);add(new THREE.BoxGeometry(.55,.65,.55),dark,.35,.9,0);add(new THREE.CylinderGeometry(.12,.16,.65,10),dark,-.35,1.05,0);for(const x of [-.45,.45])for(const z of [-.37,.37])add(new THREE.CylinderGeometry(.18,.18,.12,12),dark,x,.25,z,Math.PI/2)}
 else if(d.kind==='books'){for(let i=0;i<4;i++)add(new THREE.BoxGeometry(1.25,.18,.8),new THREE.MeshStandardMaterial({color:PALETTE[(i+2)%PALETTE.length],roughness:.85}),0,.12+i*.2,0,0,(i-1.5)*.05,(i-1.5)*.03)}
 else if(d.kind==='canopy'){add(new THREE.BoxGeometry(3,.5,4),dark,0,.4,0);add(new THREE.BoxGeometry(2.8,.42,3.7),cream,0,.85,0);for(const x of [-1.35,1.35])for(const z of [-1.8,1.8])add(new THREE.CylinderGeometry(.05,.07,3.3,8),dark,x,1.9,z);add(new THREE.BoxGeometry(2.8,.12,3.8),mat,0,3.5,0)}
 else if(d.kind==='sofa'){add(new THREE.BoxGeometry(3,.55,1.5),dark,0,.45,0);add(new THREE.BoxGeometry(2.7,.5,1.25),mat,0,.9,0);add(new THREE.BoxGeometry(2.8,1.35,.4),mat,0,1.5,.55);for(const x of [-1.35,1.35])add(new THREE.BoxGeometry(.35,.8,1.35),mat,x,.95,0)}
 else if(d.kind==='sectional'){add(new THREE.BoxGeometry(3.6,.48,1.5),dark,0,.4,0);add(new THREE.BoxGeometry(3.25,.48,1.25),mat,0,.86,0);add(new THREE.BoxGeometry(3.45,1.25,.35),mat,0,1.48,.56);add(new THREE.BoxGeometry(1.25,.48,2.65),mat,1.18,.86,-.68);for(const x of [-1.65,1.65])add(new THREE.BoxGeometry(.3,.72,1.3),mat,x,.98,0)}
 else if(d.kind==='armchair'){add(new THREE.BoxGeometry(1.65,.5,1.55),dark,0,.42,0);add(new THREE.BoxGeometry(1.35,.5,1.25),mat,0,.92,0);add(new THREE.BoxGeometry(1.45,1.5,.38),mat,0,1.62,.52,-.08);for(const x of [-.78,.78])add(new THREE.BoxGeometry(.28,.82,1.35),mat,x,1,0)}
 else if(d.kind==='coffeetable'){add(new THREE.BoxGeometry(2.6,.2,1.5),mat,0,.78,0);for(const x of [-1.05,1.05])for(const z of [-.5,.5])add(new THREE.CylinderGeometry(.09,.12,.75,8),dark,x,.38,z);add(new THREE.BoxGeometry(2.2,.1,1.1),dark,0,.28,0)}
 else if(d.kind==='tallbookcase'||d.kind==='lowbookcase'){const tall=d.kind==='tallbookcase',h=tall?4.2:1.7,w=tall?2.4:3.3;add(new THREE.BoxGeometry(w,h,.72),mat,0,h/2,0);for(let i=0;i<(tall?5:2);i++){const y=.45+i*(tall?.78:.72);add(new THREE.BoxGeometry(w-.2,.1,.75),dark,0,y,.02);for(let j=0;j<(tall?5:7);j++){const bh=.35+(j%3)*.12;add(new THREE.BoxGeometry(.18,bh,.5),new THREE.MeshStandardMaterial({color:PALETTE[(i+j)%PALETTE.length],roughness:.82}),-w/2+.3+j*(w-.55)/(tall?4:6),y+.08+bh/2,.12)}}}
 else if(d.kind==='cubestorage'){add(new THREE.BoxGeometry(3,2.5,.75),mat,0,1.25,0);for(const x of [-.5,.5])add(new THREE.BoxGeometry(.1,2.3,.8),dark,x,1.25,.02);for(const y of [.83,1.67])add(new THREE.BoxGeometry(2.8,.1,.8),dark,0,y,.02);for(let i=0;i<4;i++)add(new THREE.BoxGeometry(.65,.55,.55),new THREE.MeshStandardMaterial({color:PALETTE[(i+1)%PALETTE.length],roughness:.9}),-.92+(i%3)*.92,.38+Math.floor(i/3)*.82,.14)}
 else if(d.kind==='deskchair'){add(new THREE.CylinderGeometry(.65,.7,.18,20),mat,0,1.05,0);add(new THREE.BoxGeometry(1.25,1.35,.22),mat,0,1.75,.5,-.12);add(new THREE.CylinderGeometry(.08,.1,.85,8),dark,0,.55,0);for(let i=0;i<5;i++){const a=i*Math.PI*2/5;add(new THREE.BoxGeometry(.65,.07,.09),dark,Math.cos(a)*.3,.12,Math.sin(a)*.3,0,-a,0);add(new THREE.SphereGeometry(.09,8,6),dark,Math.cos(a)*.62,.08,Math.sin(a)*.62)}}
 else if(d.kind==='filing'){add(new THREE.BoxGeometry(1.4,1.7,1.15),mat,0,.85,0);for(let i=0;i<3;i++){add(new THREE.BoxGeometry(1.18,.45,.07),dark,0,.4+i*.52,.61);add(new THREE.BoxGeometry(.34,.05,.08),cream,0,.4+i*.52,.68)}}
 else if(d.kind==='deskset'){add(new THREE.BoxGeometry(3.7,.18,1.5),mat,0,1.72,0);for(const x of [-1.55,1.55])add(new THREE.BoxGeometry(.18,1.65,1.25),dark,x,.86,0);add(new THREE.BoxGeometry(1.05,1.2,.15),dark,0,2.42,.12);add(new THREE.BoxGeometry(.88,.95,.04),new THREE.MeshBasicMaterial({color:0x8ab8bd}),0,2.42,.22);add(new THREE.BoxGeometry(1.6,.08,.55),cream,0,1.86,-.08)}
 else if(d.kind==='wardrobe'){add(new THREE.BoxGeometry(2.7,3.8,1.15),mat,0,1.9,0);add(new THREE.BoxGeometry(.06,3.45,1.0),dark,0,2,.59);for(const x of [-.22,.22])add(new THREE.SphereGeometry(.07,10,8),cream,x,2,.65);add(new THREE.BoxGeometry(2.85,.18,1.3),dark,0,.12,0)}
 else if(d.kind==='nightstand'){add(new THREE.BoxGeometry(1.35,1.25,1.1),mat,0,.82,0);add(new THREE.BoxGeometry(1.15,.08,.08),dark,0,1,.58);add(new THREE.SphereGeometry(.06,8,6),cream,0,1,.65);for(const x of [-.5,.5])for(const z of [-.4,.4])add(new THREE.CylinderGeometry(.06,.08,.35,8),dark,x,.2,z)}
 else if(d.kind==='ottoman'){add(new THREE.CylinderGeometry(.85,.9,.6,20),mat,0,.32,0);add(new THREE.TorusGeometry(.7,.035,8,24),cream,0,.62,0,Math.PI/2)}
 else if(d.kind==='cushion'){const pillow=add(new THREE.SphereGeometry(.72,24,16),mat,0,.38,0);pillow.scale.set(1.15,.48,.92);add(new THREE.TorusGeometry(.66,.025,7,28),cream,0,.4,0,Math.PI/2);add(new THREE.CylinderGeometry(.07,.07,.05,12),dark,0,.73,0);for(const a of [0,Math.PI/2])add(new THREE.BoxGeometry(1.05,.018,.035),cream,0,.735,0,0,a,0)}
 else if(d.kind==='toybox'){add(new THREE.BoxGeometry(2.3,1.1,1.3),mat,0,.55,0);add(new THREE.BoxGeometry(2.4,.18,1.4),dark,0,1.2,-.08,-.18);for(const x of [-.8,.8])add(new THREE.BoxGeometry(.3,.3,.04),cream,x,.55,.67)}
 else if(d.kind==='dresser'){add(new THREE.BoxGeometry(2.5,1.8,1),mat,0,.9,0);for(let i=0;i<3;i++){add(new THREE.BoxGeometry(2.2,.42,.06),dark,0,.45+i*.55,.53);add(new THREE.SphereGeometry(.055,8,6),cream,0,.45+i*.55,.61)}add(new THREE.TorusGeometry(.72,.08,10,30),dark,0,2.75,.1);add(new THREE.CircleGeometry(.64,30),new THREE.MeshStandardMaterial({color:0xbdd4d2,metalness:.3,roughness:.2}),0,2.75,.12)}
 else if(d.kind==='lantern'){add(new THREE.CylinderGeometry(.65,.65,1.35,16),new THREE.MeshStandardMaterial({color:d.color,transparent:true,opacity:.72,roughness:.8}),0,.9,0);for(const y of [.25,1.55])add(new THREE.TorusGeometry(.65,.035,8,20),dark,0,y,0,Math.PI/2);const b=add(new THREE.SphereGeometry(.13,12,8),new THREE.MeshBasicMaterial({color:0xffc66d}),0,.9,0);b.userData.glow=true}
 else if(d.kind==='candles'){for(let i=0;i<3;i++){const x=(i-1)*.38,h=.55+i*.22;add(new THREE.CylinderGeometry(.12,.14,h,12),cream,x,h/2,0);const f=add(new THREE.SphereGeometry(.08,10,7),new THREE.MeshBasicMaterial({color:0xffa43b}),x,h+.08,0);f.scale.y=1.6;f.userData.glow=true}}
 else if(d.kind==='lavalamp'){add(new THREE.CylinderGeometry(.38,.5,.24,16),dark,0,.12,0);add(new THREE.CylinderGeometry(.25,.42,1.2,16),new THREE.MeshPhysicalMaterial({color:d.color,transparent:true,opacity:.75,roughness:.12}),0,.82,0);add(new THREE.SphereGeometry(.14,12,8),new THREE.MeshBasicMaterial({color:0xff9c66}),0,.85,0)}
 else if(d.kind==='camera'){add(new THREE.BoxGeometry(1.2,.75,.45),mat,0,.52,0);add(new THREE.CylinderGeometry(.28,.33,.32,18),dark,0,.52,.35,Math.PI/2);add(new THREE.CylinderGeometry(.19,.19,.34,18),new THREE.MeshPhysicalMaterial({color:0x90b7bd,metalness:.4,roughness:.15}),0,.52,.52,Math.PI/2);add(new THREE.BoxGeometry(.3,.16,.2),cream,.32,.98,0)}
 else if(d.kind==='monitor'){add(new THREE.BoxGeometry(1.65,1.1,.16),dark,0,1,.05);add(new THREE.BoxGeometry(1.45,.88,.035),new THREE.MeshBasicMaterial({color:0x83afb6}),0,1,.15);add(new THREE.CylinderGeometry(.07,.1,.52,8),dark,0,.28,0);add(new THREE.BoxGeometry(.85,.08,.55),dark,0,.05,0)}
 else if(d.kind==='laptop'){add(new RoundedBoxGeometry(1.55,.08,1.05,3,.04),dark,0,.06,0);add(new THREE.BoxGeometry(1.5,.9,.08),dark,0,.52,-.47,-.18);add(new THREE.BoxGeometry(1.32,.72,.025),new THREE.MeshBasicMaterial({color:0x91bbc1}),0,.53,-.53,-.18);add(new THREE.CylinderGeometry(.055,.055,1.25,10),dark,0,.12,-.47,0,0,Math.PI/2);for(let row=0;row<4;row++)for(let col=0;col<10;col++)add(new THREE.BoxGeometry(.095,.022,.065),cream,-.52+col*.116,.118,-.17+row*.09);add(new THREE.BoxGeometry(.52,.018,.24),new THREE.MeshStandardMaterial({color:0xbca98f,roughness:.55}),0,.114,.34)}
 else if(d.kind==='keyboard'){add(new THREE.BoxGeometry(1.55,.1,.58),cream,0,.06,0);for(let i=0;i<5;i++)for(let j=0;j<10;j++)add(new THREE.BoxGeometry(.1,.025,.07),dark,-.55+j*.12,.13,-.2+i*.1);add(new THREE.SphereGeometry(.2,12,8),mat,1.05,.14,.02)}
 else if(d.kind==='speakers'){for(const x of [-.55,.55]){add(new THREE.BoxGeometry(.55,1,.45),dark,x,.5,0);add(new THREE.CircleGeometry(.17,18),mat,x,.62,.231);add(new THREE.CircleGeometry(.09,14),cream,x,.28,.235)}}
 else if(d.kind==='printer'){add(new THREE.BoxGeometry(1.5,.72,1.1),mat,0,.38,0);add(new THREE.BoxGeometry(1.18,.12,.75),dark,0,.8,-.08);add(new THREE.BoxGeometry(.95,.035,.7),cream,0,.95,-.18,-.18);add(new THREE.BoxGeometry(.8,.12,.55),dark,0,.28,.55,.2)}
 else if(d.kind==='desktop'){add(new THREE.BoxGeometry(.65,1.25,.75),dark,1.15,.65,0);add(new THREE.BoxGeometry(1.65,1.1,.16),dark,-.2,1.05,.05);add(new THREE.BoxGeometry(1.43,.87,.035),new THREE.MeshBasicMaterial({color:0x7faeb5}),-.2,1.05,.15);add(new THREE.CylinderGeometry(.06,.09,.45,8),dark,-.2,.35,0);add(new THREE.BoxGeometry(.82,.07,.5),dark,-.2,.08,0);add(new THREE.BoxGeometry(1.35,.08,.48),cream,-.15,.06,.7)}
 else if(d.kind==='record'){add(new THREE.BoxGeometry(1.55,.3,1.3),mat,0,.2,0);add(new THREE.CylinderGeometry(.48,.48,.05,32),dark,-.18,.39,0);add(new THREE.CylinderGeometry(.08,.08,.08,16),cream,-.18,.43,0);add(new THREE.BoxGeometry(.08,.06,.72),cream,.48,.48,.05,0,.25,.12)}
 else if(d.kind==='musicbox'){add(new THREE.BoxGeometry(1.25,.65,.9),mat,0,.38,0);add(new THREE.BoxGeometry(1.35,.12,1),dark,0,.77,0);const dancer=add(new THREE.CylinderGeometry(.08,.12,.55,10),cream,0,1.12,0);dancer.rotation.z=.08}
 else if(d.kind==='snowglobe'){add(new THREE.CylinderGeometry(.42,.52,.28,18),dark,0,.14,0);add(new THREE.SphereGeometry(.48,20,15),new THREE.MeshPhysicalMaterial({color:0xc6e0df,transparent:true,opacity:.48,roughness:.05}),0,.68,0);add(new THREE.ConeGeometry(.18,.5,8),mat,0,.62,0)}
 else if(d.kind==='globe'){add(new THREE.SphereGeometry(.62,20,14),new THREE.MeshStandardMaterial({color:0x6a9c98,roughness:.75}),0,1.25,0);add(new THREE.TorusGeometry(.68,.045,8,28),dark,0,1.25,0,0,0,.25);add(new THREE.CylinderGeometry(.06,.08,.75,8),dark,0,.52,0);add(new THREE.CylinderGeometry(.45,.55,.12,16),dark,0,.08,0)}
 else if(d.kind==='dollhouse'){add(new THREE.BoxGeometry(1.65,1.25,.75),mat,0,.68,0);add(new THREE.ConeGeometry(1.25,.85,4),dark,0,1.72,0,0,Math.PI/4);for(const x of [-.45,.45])add(new THREE.BoxGeometry(.35,.42,.06),cream,x,.72,.41)}
 else if(d.kind==='roundrug'){const r=add(new THREE.CylinderGeometry(1.7,1.7,.04,32),mat,0,.025,0);r.receiveShadow=true;for(const s of [.55,1.05,1.45])add(new THREE.TorusGeometry(s,.035,6,32),cream,0,.06,0,Math.PI/2)}
 else if(d.kind==='mirror'){add(new THREE.BoxGeometry(1.8,.18,.72),dark,0,.09,0);for(const x of [-.62,.62])add(new THREE.BoxGeometry(.18,.72,.5),dark,x,.44,0,0,0,x<0?-.12:.12);add(new THREE.BoxGeometry(1.55,2.95,.18),dark,0,2.05,0);add(new THREE.BoxGeometry(1.28,2.66,.04),new THREE.MeshPhysicalMaterial({color:0xb9d6d8,metalness:.28,roughness:.08,clearcoat:1,clearcoatRoughness:.06}),0,2.05,.115);add(new THREE.BoxGeometry(.08,2.35,.025),new THREE.MeshBasicMaterial({color:0xeaf8f4,transparent:true,opacity:.55}),-.43,2.08,.142,0,0,-.035)}
 else if(d.kind==='clock'){add(new THREE.BoxGeometry(1.25,.9,.42),mat,0,.52,0);add(new THREE.CircleGeometry(.32,24),cream,0,.58,.23);for(let i=0;i<4;i++)add(new THREE.BoxGeometry(.035,.18,.03),dark,Math.sin(i*Math.PI/2)*.22,.58+Math.cos(i*Math.PI/2)*.22,.25,0,0,-i*Math.PI/2)}
 else if(d.kind==='basket'){const weave=new THREE.MeshStandardMaterial({color:d.color,roughness:.95,side:THREE.DoubleSide});add(new THREE.CylinderGeometry(.72,.56,.78,24,3,true),weave,0,.4,0);add(new THREE.CylinderGeometry(.53,.48,.08,24),dark,0,.08,0);add(new THREE.TorusGeometry(.72,.065,8,28),dark,0,.79,0,Math.PI/2);add(new THREE.TorusGeometry(.57,.065,8,24,Math.PI),dark,0,.8,0);for(let i=0;i<7;i++)add(new THREE.TorusGeometry(.57-i*.012,.018,5,24),cream,0,.18+i*.09,0,Math.PI/2)}
 else if(d.kind==='plant'||d.kind==='flowers'){add(new THREE.CylinderGeometry(.38,.28,.7,16),mat,0,.38,0);for(let i=0;i<(d.kind==='plant'?11:7);i++){const a=i*2.4,r=.3+(i%3)*.1;const stem=add(new THREE.CylinderGeometry(.025,.035,.8,6),new THREE.MeshStandardMaterial({color:0x55704d}),Math.cos(a)*r*.35,1,Math.sin(a)*r*.35,Math.sin(a)*.35,0,Math.cos(a)*.35);if(d.kind==='flowers')add(new THREE.SphereGeometry(.14,10,8),new THREE.MeshStandardMaterial({color:PALETTE[i%PALETTE.length]}),stem.position.x,1.45,stem.position.z)} }
 else if(d.kind==='cactus'||d.kind==='monstera'||d.kind==='mushroom'){add(new THREE.CylinderGeometry(.42,.3,.62,14),mat,0,.32,0);const green=new THREE.MeshStandardMaterial({color:d.kind==='mushroom'?0xdba58d:0x577b55,roughness:.85});if(d.kind==='cactus'){add(new THREE.CapsuleGeometry(.22,.85,5,10),green,0,1.15,0);for(const x of [-.28,.28])add(new THREE.CapsuleGeometry(.11,.38,4,8),green,x,1.2,0,0,0,x>0?-.55:.55)}else if(d.kind==='monstera'){for(let i=0;i<8;i++){const a=i*.78;add(new THREE.SphereGeometry(.3,10,8),green,Math.cos(a)*.5,1+Math.sin(a*.7)*.5,Math.sin(a)*.5,0,a,0)}}else{for(let i=0;i<5;i++){const x=(i-2)*.25;add(new THREE.CylinderGeometry(.06,.08,.45,8),cream,x,.85,0);add(new THREE.SphereGeometry(.22,12,8,0,Math.PI*2,0,Math.PI/2),green,x,1.08,0)}}}
 g.position.set(d.x,d.y??0,d.z);g.rotation.y=d.rot;g.scale.setScalar(d.scale??1);return g}
 private ownerOf(o:THREE.Object3D){let owner=o;while(owner.parent&&!owner.userData.itemId)owner=owner.parent;return owner.userData.itemId?owner as THREE.Group:undefined}
 private supportTop(g:THREE.Group){const d=this.data.find(x=>x.id===g.userData.itemId);return g.position.y+(SUPPORT_HEIGHTS[d?.kind??'']??new THREE.Box3().setFromObject(g).max.y-g.position.y)*(d?.scale??1)}
 private pointerDown(e:PointerEvent){if((e.target as HTMLElement)!==this.canvas)return;this.setPointer(e);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects([...this.items.values()],true);if(hits.length){const g=this.ownerOf(hits[0].object);if(!g)return;this.select(g);this.checkpoint();this.drag=true;this.controls.enabled=false;const d=this.data.find(x=>x.id===g.userData.itemId);this.dragHeight=d?.supportId?0:g.position.y;const hit=new THREE.Vector3();this.ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-this.dragHeight),hit);this.dragOffset.copy(g.position).sub(hit);this.canvas.setPointerCapture(e.pointerId)}else this.select(undefined)}
 private pointerMove(e:PointerEvent){if(!this.drag||!this.selected)return;this.setPointer(e);this.ray.setFromCamera(this.pointer,this.camera);const d=this.findData();if(!d)return;const oldX=d.x,oldZ=d.z;let support:THREE.Group|undefined;if(!FLOOR_ONLY_KINDS.has(d.kind)){for(const h of this.ray.intersectObjects([...this.items.values()].filter(g=>g!==this.selected),true)){const candidate=this.ownerOf(h.object);const candidateData=this.data.find(x=>x.id===candidate?.userData.itemId);if(candidate&&candidateData&&SUPPORT_KINDS.has(candidateData.kind)){support=candidate;break}}}if(support){const top=this.supportTop(support);const plane=new THREE.Plane(new THREE.Vector3(0,1,0),-top);const hit=new THREE.Vector3();if(this.ray.ray.intersectPlane(plane,hit)){d.x=THREE.MathUtils.clamp(hit.x,-5.7,5.7);d.z=THREE.MathUtils.clamp(hit.z,-4.5,4.5);d.y=top+.025;d.supportId=support.userData.itemId}}else{const hit=new THREE.Vector3();if(this.ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-this.dragHeight),hit)){hit.add(this.dragOffset);d.x=THREE.MathUtils.clamp(hit.x,-5.7,5.7);d.z=THREE.MathUtils.clamp(hit.z,-4.5,4.5);d.y=this.dragHeight;d.supportId=undefined}}this.selected.position.set(d.x,d.y??0,d.z);if(SUPPORT_KINDS.has(d.kind)){const dx=d.x-oldX,dz=d.z-oldZ;for(const child of this.data.filter(x=>x.supportId===d.id)){child.x+=dx;child.z+=dz;child.y=this.supportTop(this.selected)+.025;const childGroup=this.items.get(child.id);if(childGroup)childGroup.position.set(child.x,child.y,child.z)}}document.querySelector('#prompt')!.textContent=d.supportId?'Release to place on top.':this.dragHeight?`Moving at height ${this.dragHeight.toFixed(1)}.`:'Move it anywhere in the room.'}
 private pointerUp(){if(this.drag){this.drag=false;this.controls.enabled=true;this.audio('place');this.changed()}}
 private setPointer(e:PointerEvent){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1)}
 private clearSelectionGlow(){if(!this.selected)return;const glows:THREE.LineSegments[]=[];this.selected.traverse(o=>{if(o instanceof THREE.LineSegments&&o.userData.selectionGlow)glows.push(o);else if(o instanceof THREE.Mesh){const m=o.material as THREE.MeshStandardMaterial;if(m.emissive){m.emissive.setHex(0);m.emissiveIntensity=1}}});for(const glow of glows){glow.removeFromParent();glow.geometry.dispose();(glow.material as THREE.Material).dispose()}}
 private select(g?:THREE.Group){this.clearSelectionGlow();this.selected=g;document.querySelector('#selection')?.classList.toggle('hidden',!g);if(g){document.querySelector('#selected-name')!.textContent=g.name;const meshes:THREE.Mesh[]=[];g.traverse(o=>{if(o instanceof THREE.Mesh)meshes.push(o)});for(const mesh of meshes){const m=mesh.material as THREE.MeshStandardMaterial;if(m.emissive){m.emissive.setHex(0x7a3e12);m.emissiveIntensity=.28}const outline=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry,28),new THREE.LineBasicMaterial({color:0xffd27a,transparent:true,opacity:.8,depthTest:false,blending:THREE.AdditiveBlending,toneMapped:false}));outline.userData.selectionGlow=true;outline.renderOrder=999;outline.scale.setScalar(1.018);mesh.add(outline)}}}
 private findData(){return this.data.find(x=>x.id===this.selected?.userData.itemId)} private modify(n:number){const d=this.findData();if(!d||!this.selected)return;this.checkpoint();d.rot+=n;this.selected.rotation.y=d.rot;if(SUPPORT_KINDS.has(d.kind)){const c=Math.cos(n),s=Math.sin(n);for(const child of this.data.filter(x=>x.supportId===d.id)){const x=child.x-d.x,z=child.z-d.z;child.x=d.x+x*c-z*s;child.z=d.z+x*s+z*c;this.items.get(child.id)?.position.set(child.x,child.y??0,child.z)}}this.changed()} private adjustHeight(n:number){const d=this.findData();if(!d||!this.selected)return;const oldY=d.y??0,nextY=THREE.MathUtils.clamp(oldY+n,0,6),delta=nextY-oldY;if(!delta)return;this.checkpoint();d.y=nextY;d.supportId=undefined;this.selected.position.y=d.y;if(SUPPORT_KINDS.has(d.kind)){for(const child of this.data.filter(x=>x.supportId===d.id)){child.y=THREE.MathUtils.clamp((child.y??0)+delta,0,6);this.items.get(child.id)?.position.set(child.x,child.y,child.z)}}document.querySelector('#selected-name')!.textContent=`${d.name} · ${d.y.toFixed(1)} high`;this.audio('place');this.changed()} private resizeSelected(n:number){const d=this.findData();if(!d||!this.selected)return;this.checkpoint();d.scale=THREE.MathUtils.clamp((d.scale??1)+n,.55,1.6);this.selected.scale.setScalar(d.scale);if(SUPPORT_KINDS.has(d.kind)){const top=this.supportTop(this.selected)+.025;for(const child of this.data.filter(x=>x.supportId===d.id)){child.y=top;const g=this.items.get(child.id);if(g)g.position.y=top}}this.changed()}
 private recolor(){const d=this.findData();if(!d||!this.selected)return;this.checkpoint();d.color=PALETTE[(PALETTE.indexOf(d.color)+1)%PALETTE.length];this.rebuild();this.changed()}
 private duplicate(){const d=this.findData();if(!d)return;const c=CATALOG.find(x=>x.kind===d.kind)!;this.add(c,{...d,id:crypto.randomUUID(),x:d.x+.6,z:d.z+.5})}
 private remove(){const d=this.findData();if(!d||!this.selected)return;this.checkpoint();for(const child of this.data.filter(x=>x.supportId===d.id)){child.supportId=undefined;child.y=0;const g=this.items.get(child.id);if(g)g.position.y=0}this.scene.remove(this.selected);this.items.delete(d.id);this.data=this.data.filter(x=>x.id!==d.id);this.select(undefined);this.audio('remove');this.changed()}
 private checkpoint(){this.history.push(structuredClone(this.data));if(this.history.length>30)this.history.shift();this.future=[];this.updateButtons()} private undo(){const s=this.history.pop();if(!s)return;this.future.push(structuredClone(this.data));this.data=s;this.rebuild();this.changed()} private redo(){const s=this.future.pop();if(!s)return;this.history.push(structuredClone(this.data));this.data=s;this.rebuild();this.changed()}
 private rebuild(){const selectedId=this.selected?.userData.itemId;this.select(undefined);this.items.forEach(g=>this.scene.remove(g));this.items.clear();for(const d of this.data){const g=this.makeItem(d);this.items.set(d.id,g);this.scene.add(g)}if(selectedId)this.select(this.items.get(selectedId));this.updateButtons()}
 private updateButtons(){(document.querySelector('#undo') as HTMLButtonElement).disabled=!this.history.length;(document.querySelector('#redo') as HTMLButtonElement).disabled=!this.future.length}
 private changed(){clearTimeout(this.saveTimer);this.saveTimer=window.setTimeout(()=>{localStorage.setItem('my-little-room-v1',JSON.stringify(this.data));const t=document.querySelector('#toast')!;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)},450);const p=document.querySelector('#prompt')!;p.textContent=this.data.length<3?`Add ${3-this.data.length} little thing${3-this.data.length===1?'':'s'} that feel like home.`:'Lovely. This room is becoming yours.';this.publish();this.updateButtons()}
 private load(){try{const raw=localStorage.getItem('my-little-room-v1');const saved=raw===null?null:JSON.parse(raw) as ItemData[]|null;if(Array.isArray(saved)){this.data=saved;this.rebuild();return}}catch{};const starters=[['bed',-3.8,-2.4],['lamp',-5,-3.8],['desk',3.7,-3.8],['plant',4.8,-4.1],['teddy',-1.2,2.2],['books',2,2.7]] as const;for(const [kind,x,z] of starters){const c=CATALOG.find(q=>q.kind===kind)!;this.add(c,{x,z},false)}this.history=[];this.updateButtons()}
 private toggleTime(){this.evening=!this.evening;(this.scene.background as THREE.Color).setHex(this.evening?0x313747:0x9fa9a1);(this.scene.fog as THREE.Fog).color.setHex(this.evening?0x42404a:0xb9b4a5);if(this.keyLight)this.keyLight.intensity=this.evening?42:80;if(this.lampLight)this.lampLight.intensity=this.evening?14:5;(document.querySelector('#time-toggle')!).textContent=this.evening?'☾ Evening':'☀ Afternoon';this.audio('chime')}
 private resetCamera(){this.camera.position.set(12,10,15);this.controls.target.set(0,2.3,0);this.controls.update()}
 private audio(type:string){if(type==='begin'){this.ambience.loop=true;this.ambience.volume=.16;void this.ambience.play().catch(()=>{})}const A=window.AudioContext||(window as any).webkitAudioContext;if(!A)return;const ctx=new A();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=type==='remove'?190:type==='place'?420:620;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.045,ctx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.32);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.35)}
 private update(_d:number,e:number){resizeRenderer(this.renderer,this.camera,matchMedia('(pointer:coarse)').matches?1.35:1.7);this.controls.update();if(this.dust){this.dust.rotation.y=e*.015;this.dust.position.y=Math.sin(e*.2)*.04}this.items.forEach(g=>{g.traverse(o=>{if(o.userData.glow)o.scale.setScalar(1+Math.sin(e*2)*.06);if(o instanceof THREE.LineSegments&&o.userData.selectionGlow)(o.material as THREE.LineBasicMaterial).opacity=.62+(Math.sin(e*4)+1)*.16})});this.publish()}
 private publish(){const info=this.renderer.info.render;window.__THREE_GAME_DIAGNOSTICS__={frame:(window.__THREE_GAME_DIAGNOSTICS__?.frame||0)+1,fps:0,frameTimeMs:0,state:this.selected?'editing':'decorating',player:{position:{x:this.selected?.position.x||0,y:0,z:this.selected?.position.z||0}},entities:{pickups:this.data.length,total:this.data.length+1},renderer:{calls:info.calls,triangles:info.triangles,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures}}}
}
