import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { Loop } from '../core/Loop';
import { createRenderer, resizeRenderer } from '../core/Renderer';

type Category='furniture'|'light'|'keepsake'|'plant';
type ItemData={id:string;kind:string;name:string;category:Category;x:number;z:number;rot:number;color:number};
type CatalogItem={kind:string;name:string;category:Category;icon:string;note:string};

const CATALOG:CatalogItem[]=[
 {kind:'bed',name:'Patchwork bed',category:'furniture',icon:'🛏️',note:'Soft & sleepy'},
 {kind:'desk',name:'Writing desk',category:'furniture',icon:'🪵',note:'For little letters'},
 {kind:'chair',name:'Sunday chair',category:'furniture',icon:'🪑',note:'A quiet corner'},
 {kind:'shelf',name:'Memory shelf',category:'furniture',icon:'📚',note:'Treasures live here'},
 {kind:'lamp',name:'Honey lamp',category:'light',icon:'💡',note:'Warm evening glow'},
 {kind:'fairy',name:'Fairy lights',category:'light',icon:'✨',note:'Tiny constellations'},
 {kind:'teddy',name:'Old teddy',category:'keepsake',icon:'🧸',note:'A faithful friend'},
 {kind:'radio',name:'Pocket radio',category:'keepsake',icon:'📻',note:'Songs after school'},
 {kind:'train',name:'Wooden train',category:'keepsake',icon:'🚂',note:'Still runs on dreams'},
 {kind:'books',name:'Story books',category:'keepsake',icon:'📚',note:'Dog-eared favorites'},
 {kind:'plant',name:'Window fern',category:'plant',icon:'🌿',note:'Something growing'},
 {kind:'flowers',name:'Jam-jar flowers',category:'plant',icon:'🌼',note:'From the garden'},
];
const PALETTE=[0xb75e4b,0x6f8875,0xd7a34c,0x66858d,0xd8a69a,0x8b6048];

export class Game{
 private renderer:THREE.WebGLRenderer; private scene=new THREE.Scene(); private camera=new THREE.PerspectiveCamera(36,1,.1,100); private controls:OrbitControls;
 private loop=new Loop((d,e)=>this.update(d,e),()=>this.renderer.render(this.scene,this.camera)); private ray=new THREE.Raycaster(); private pointer=new THREE.Vector2();
 private items=new Map<string,THREE.Group>(); private data:ItemData[]=[]; private selected?:THREE.Group; private drag=false; private dragOffset=new THREE.Vector3(); private history:ItemData[][]=[]; private future:ItemData[][]=[];
 private floorTex?:THREE.Texture; private evening=false; private keyLight?:THREE.SpotLight; private lampLight?:THREE.PointLight; private dust?:THREE.Points; private saveTimer=0;
 constructor(private canvas:HTMLCanvasElement){this.renderer=createRenderer(canvas);this.renderer.toneMappingExposure=1.12;this.camera.position.set(12,10,15);this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(0,2.3,0);this.controls.enableDamping=true;this.controls.minDistance=10;this.controls.maxDistance=28;this.controls.maxPolarAngle=Math.PI*.48;this.controls.minPolarAngle=.45;this.createWorld();this.bindUI();this.load();resizeRenderer(this.renderer,this.camera,1.7);this.publish()}
 start(){this.loop.start()} dispose(){this.loop.stop();this.controls.dispose();this.renderer.dispose();clearTimeout(this.saveTimer)}
 private createWorld(){this.scene.background=new THREE.Color(0x9fa9a1);this.scene.fog=new THREE.Fog(0xb9b4a5,24,46);const hemi=new THREE.HemisphereLight(0xc9dddf,0x5b382b,1.9);this.scene.add(hemi);this.keyLight=new THREE.SpotLight(0xffd69b,80,35,.65,.5,1.3);this.keyLight.position.set(-5,10,6);this.keyLight.target.position.set(0,0,0);this.keyLight.castShadow=true;this.keyLight.shadow.mapSize.set(1024,1024);this.scene.add(this.keyLight,this.keyLight.target);const fill=new THREE.DirectionalLight(0xaed7e6,1.6);fill.position.set(8,7,-4);this.scene.add(fill);this.lampLight=new THREE.PointLight(0xffa94e,5,10,2);this.lampLight.position.set(-4,4,-3);this.scene.add(this.lampLight);
 const room=new THREE.Group();const floorMat=new THREE.MeshStandardMaterial({color:0x8d6548,roughness:.72});const floor=new THREE.Mesh(new THREE.BoxGeometry(14,.28,11),floorMat);floor.receiveShadow=true;floor.position.y=-.15;room.add(floor);for(let i=-6;i<=6;i++){const seam=new THREE.Mesh(new THREE.BoxGeometry(.025,.01,10.8),new THREE.MeshBasicMaterial({color:0x5e4435,transparent:true,opacity:.32}));seam.position.set(i,0.005,0);room.add(seam)}const wallMat=new THREE.MeshStandardMaterial({color:0xe8d7b8,roughness:.92});const back=new THREE.Mesh(new THREE.BoxGeometry(14,7,.18),wallMat);back.position.set(0,3.5,-5.45);back.receiveShadow=true;room.add(back);const side=new THREE.Mesh(new THREE.BoxGeometry(.18,7,11),wallMat);side.position.set(-6.9,3.5,0);side.receiveShadow=true;room.add(side);const baseMat=new THREE.MeshStandardMaterial({color:0xf2e5cf,roughness:.7});const base1=new THREE.Mesh(new THREE.BoxGeometry(14,.32,.22),baseMat);base1.position.set(0,.18,-5.3);room.add(base1);const base2=new THREE.Mesh(new THREE.BoxGeometry(.22,.32,11),baseMat);base2.position.set(-6.75,.18,0);room.add(base2);this.addWindow(room);this.addBuiltIns(room);this.scene.add(room);this.addRug();this.addDust();}
 private addWindow(room:THREE.Group){const frameMat=new THREE.MeshStandardMaterial({color:0xf3e8d1,roughness:.55});const glass=new THREE.Mesh(new THREE.PlaneGeometry(4.2,3),new THREE.MeshBasicMaterial({color:0xa9d5dc}));glass.position.set(2.4,4,-5.34);room.add(glass);for(const [x,y,w,h] of [[2.4,5.55,4.7,.18],[2.4,2.45,4.7,.18],[.05+0,4,.18,3.3],[4.75,4,.18,3.3],[2.4,4,.14,3.1],[2.4,4,4.4,.12]] as number[][]){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,.18),frameMat);m.position.set(x,y,-5.18);room.add(m)}const curtainMat=new THREE.MeshStandardMaterial({color:0xc98270,roughness:1,side:THREE.DoubleSide});for(const x of [-.35,5.15]){const c=new THREE.Mesh(new THREE.PlaneGeometry(1.1,3.8,6,8),curtainMat);c.position.set(x,4,-5.05);c.rotation.y=x<0?.18:-.18;room.add(c)}}
 private addBuiltIns(room:THREE.Group){const wood=new THREE.MeshStandardMaterial({color:0x6f4935,roughness:.62});const shelf=new THREE.Mesh(new THREE.BoxGeometry(3,.18,.75),wood);shelf.position.set(-4.7,4.3,-5);shelf.castShadow=true;room.add(shelf);for(let i=0;i<4;i++){const book=new THREE.Mesh(new THREE.BoxGeometry(.28,.7,.55),new THREE.MeshStandardMaterial({color:PALETTE[i],roughness:.85}));book.position.set(-5.5+i*.35,4.75,-5);book.rotation.z=(i-1.5)*.04;room.add(book)}const posters=[0xd19b78,0x78928b,0xd7b363];posters.forEach((c,i)=>{const frame=new THREE.Mesh(new THREE.BoxGeometry(1.25,1.55,.08),wood);frame.position.set(-6.72,3.3+i*1.25,2.6-i*1.35);frame.rotation.y=Math.PI/2;room.add(frame);const art=new THREE.Mesh(new THREE.PlaneGeometry(1.05,1.35),new THREE.MeshBasicMaterial({color:c}));art.position.set(-6.66,3.3+i*1.25,2.6-i*1.35);art.rotation.y=Math.PI/2;room.add(art)})}
 private addRug(){this.floorTex=new THREE.TextureLoader().load(`${import.meta.env.BASE_URL}assets/rug-memory.png`);this.floorTex.colorSpace=THREE.SRGBColorSpace;const rug=new THREE.Mesh(new THREE.PlaneGeometry(7.6,5.8),new THREE.MeshStandardMaterial({map:this.floorTex,roughness:1}));rug.rotation.x=-Math.PI/2;rug.position.set(.6,.025,.5);rug.receiveShadow=true;this.scene.add(rug)}
 private addDust(){const geo=new THREE.BufferGeometry();const p=[];for(let i=0;i<110;i++)p.push((Math.random()-.5)*13,Math.random()*6,(Math.random()-.5)*10);geo.setAttribute('position',new THREE.Float32BufferAttribute(p,3));this.dust=new THREE.Points(geo,new THREE.PointsMaterial({color:0xffe2a8,size:.035,transparent:true,opacity:.5}));this.scene.add(this.dust)}
 private bindUI(){const $=(s:string)=>document.querySelector<HTMLElement>(s)!;$('#begin').onclick=()=>{$('#welcome').classList.add('gone');this.audio('begin')};$('#open-catalog').onclick=()=>$('#catalog').classList.remove('closed');$('#close-catalog').onclick=()=>$('#catalog').classList.add('closed');$('#reset-view').onclick=()=>this.resetCamera();$('#time-toggle').onclick=()=>this.toggleTime();$('#undo').onclick=()=>this.undo();$('#redo').onclick=()=>this.redo();$('#rotate-left').onclick=()=>this.modify(-Math.PI/12);$('#rotate-right').onclick=()=>this.modify(Math.PI/12);$('#color').onclick=()=>this.recolor();$('#duplicate').onclick=()=>this.duplicate();$('#remove').onclick=()=>this.remove();$('#sound').onclick=()=>this.audio('chime');document.querySelectorAll<HTMLButtonElement>('#categories button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#categories button').forEach(x=>x.classList.remove('active'));b.classList.add('active');this.renderCatalog((b.dataset.cat||'all') as Category|'all')});this.renderCatalog('all');this.canvas.addEventListener('pointerdown',e=>this.pointerDown(e));this.canvas.addEventListener('pointermove',e=>this.pointerMove(e));window.addEventListener('pointerup',()=>this.pointerUp());window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?this.redo():this.undo()}else if(e.key==='Delete'||e.key==='Backspace')this.remove();else if(e.key.toLowerCase()==='q')this.modify(-Math.PI/12);else if(e.key.toLowerCase()==='e')this.modify(Math.PI/12);else if(e.key==='Escape')this.select(undefined)})}
 private renderCatalog(cat:Category|'all'){const host=document.querySelector('#items')!;host.innerHTML='';CATALOG.filter(x=>cat==='all'||x.category===cat).forEach(x=>{const b=document.createElement('button');b.className='item';b.innerHTML=`<span>${x.icon}</span>${x.name}<small>${x.note}</small>`;b.onclick=()=>{this.add(x);if(innerWidth<700)document.querySelector('#catalog')?.classList.add('closed')};host.appendChild(b)})}
 private add(c:CatalogItem,d?:Partial<ItemData>,record=true){if(record)this.checkpoint();const data:ItemData={id:d?.id||crypto.randomUUID(),kind:c.kind,name:c.name,category:c.category,x:d?.x??(Math.random()*4-1),z:d?.z??(Math.random()*3),rot:d?.rot||0,color:d?.color??PALETTE[Math.floor(Math.random()*PALETTE.length)]};const g=this.makeItem(data);this.data.push(data);this.items.set(data.id,g);this.scene.add(g);this.select(g);if(record){this.audio('place');this.changed()}return g}
 private makeItem(d:ItemData){const g=new THREE.Group();g.userData.itemId=d.id;g.name=d.name;const mat=new THREE.MeshStandardMaterial({color:d.color,roughness:.72});const cream=new THREE.MeshStandardMaterial({color:0xf1dfc1,roughness:.9});const dark=new THREE.MeshStandardMaterial({color:0x5a392b,roughness:.58});const add=(geo:THREE.BufferGeometry,m:THREE.Material,x:number,y:number,z:number,rx=0,ry=0,rz=0)=>{const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.rotation.set(rx,ry,rz);o.castShadow=true;o.receiveShadow=true;g.add(o);return o};
 if(d.kind==='bed'){add(new THREE.BoxGeometry(3,.55,4),dark,0,.45,0);add(new THREE.BoxGeometry(2.8,.45,3.65),cream,0,.95,.08);add(new THREE.BoxGeometry(2.8,.18,2.3),mat,0,1.18,.65);add(new THREE.BoxGeometry(1.15,.25,.65),cream,-.62,1.22,-1.1);add(new THREE.BoxGeometry(1.15,.25,.65),cream,.62,1.22,-1.1);}
 else if(d.kind==='desk'){add(new THREE.BoxGeometry(2.8,.22,1.4),mat,0,1.75,0);for(const x of [-1.15,1.15])for(const z of [-.5,.5])add(new THREE.CylinderGeometry(.11,.14,1.65,8),dark,x,.85,z);add(new THREE.BoxGeometry(1.2,.1,.85),cream,-.35,1.92,0,.0,0,-.08)}
 else if(d.kind==='chair'){add(new THREE.BoxGeometry(1.4,.25,1.4),mat,0,1.05,0);add(new THREE.BoxGeometry(1.4,1.8,.22),mat,0,1.85,.58,-.1);for(const x of [-.5,.5])for(const z of [-.5,.5])add(new THREE.CylinderGeometry(.1,.13,1,8),dark,x,.5,z)}
 else if(d.kind==='shelf'){for(let i=0;i<3;i++)add(new THREE.BoxGeometry(2.5,.18,.8),mat,0,.45+i*.8,0);for(const x of [-1.1,1.1])add(new THREE.BoxGeometry(.18,2.2,.8),dark,x,1.25,0)}
 else if(d.kind==='lamp'){add(new THREE.CylinderGeometry(.5,.65,.18,20),dark,0,.1,0);add(new THREE.CylinderGeometry(.07,.09,1.8,10),dark,0,1,0);add(new THREE.CylinderGeometry(.34,.72,.7,20,1,true),mat,0,2,0);const bulb=add(new THREE.SphereGeometry(.18,16,12),new THREE.MeshBasicMaterial({color:0xffd285}),0,1.88,0);bulb.userData.glow=true}
 else if(d.kind==='fairy'){for(let i=0;i<9;i++){const x=-1.8+i*.45,y=1.5+Math.sin(i*.8)*.25;add(new THREE.SphereGeometry(.08,10,8),new THREE.MeshBasicMaterial({color:PALETTE[i%PALETTE.length],toneMapped:false}),x,y,0)} }
 else if(d.kind==='teddy'){add(new THREE.SphereGeometry(.55,18,14),mat,0,.7,0);add(new THREE.SphereGeometry(.42,18,14),mat,0,1.45,0);for(const x of [-.34,.34])add(new THREE.SphereGeometry(.18,14,10),mat,x,1.75,0);for(const x of [-.25,.25])add(new THREE.SphereGeometry(.045,8,6),dark,x,1.52,.38)}
 else if(d.kind==='radio'){add(new THREE.BoxGeometry(1.5,.9,.55),mat,0,.55,0);add(new THREE.CircleGeometry(.28,20),dark,-.32,.58,.281);add(new THREE.CylinderGeometry(.08,.08,.25,10),cream,.45,.72,.32,Math.PI/2);add(new THREE.CylinderGeometry(.08,.08,.25,10),cream,.45,.42,.32,Math.PI/2)}
 else if(d.kind==='train'){add(new THREE.BoxGeometry(1.5,.5,.65),mat,0,.48,0);add(new THREE.BoxGeometry(.55,.65,.55),dark,.35,.9,0);add(new THREE.CylinderGeometry(.12,.16,.65,10),dark,-.35,1.05,0);for(const x of [-.45,.45])for(const z of [-.37,.37])add(new THREE.CylinderGeometry(.18,.18,.12,12),dark,x,.25,z,Math.PI/2)}
 else if(d.kind==='books'){for(let i=0;i<4;i++)add(new THREE.BoxGeometry(1.25,.18,.8),new THREE.MeshStandardMaterial({color:PALETTE[(i+2)%PALETTE.length],roughness:.85}),0,.12+i*.2,0,0,(i-1.5)*.05,(i-1.5)*.03)}
 else if(d.kind==='plant'||d.kind==='flowers'){add(new THREE.CylinderGeometry(.38,.28,.7,16),mat,0,.38,0);for(let i=0;i<(d.kind==='plant'?11:7);i++){const a=i*2.4,r=.3+(i%3)*.1;const stem=add(new THREE.CylinderGeometry(.025,.035,.8,6),new THREE.MeshStandardMaterial({color:0x55704d}),Math.cos(a)*r*.35,1,Math.sin(a)*r*.35,Math.sin(a)*.35,0,Math.cos(a)*.35);if(d.kind==='flowers')add(new THREE.SphereGeometry(.14,10,8),new THREE.MeshStandardMaterial({color:PALETTE[i%PALETTE.length]}),stem.position.x,1.45,stem.position.z)} }
 g.position.set(d.x,0,d.z);g.rotation.y=d.rot;return g}
 private pointerDown(e:PointerEvent){if((e.target as HTMLElement)!==this.canvas)return;this.setPointer(e);this.ray.setFromCamera(this.pointer,this.camera);const hits=this.ray.intersectObjects([...this.items.values()],true);if(hits.length){let o:THREE.Object3D=hits[0].object;while(o.parent&&!o.userData.itemId)o=o.parent;const g=o as THREE.Group;this.select(g);this.checkpoint();this.drag=true;this.controls.enabled=false;const hit=new THREE.Vector3();this.ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),hit);this.dragOffset.copy(g.position).sub(hit);this.canvas.setPointerCapture(e.pointerId)}else this.select(undefined)}
 private pointerMove(e:PointerEvent){if(!this.drag||!this.selected)return;this.setPointer(e);this.ray.setFromCamera(this.pointer,this.camera);const hit=new THREE.Vector3();if(this.ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),hit)){hit.add(this.dragOffset);this.selected.position.x=THREE.MathUtils.clamp(hit.x,-5.7,5.7);this.selected.position.z=THREE.MathUtils.clamp(hit.z,-4.5,4.5);const d=this.findData();if(d){d.x=this.selected.position.x;d.z=this.selected.position.z}}}
 private pointerUp(){if(this.drag){this.drag=false;this.controls.enabled=true;this.audio('place');this.changed()}}
 private setPointer(e:PointerEvent){const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1)}
 private select(g?:THREE.Group){if(this.selected)this.selected.traverse(o=>{if(o instanceof THREE.Mesh){const m=o.material as THREE.MeshStandardMaterial;if(m.emissive)m.emissive.setHex(0)}});this.selected=g;document.querySelector('#selection')?.classList.toggle('hidden',!g);if(g){document.querySelector('#selected-name')!.textContent=g.name;g.traverse(o=>{if(o instanceof THREE.Mesh){const m=o.material as THREE.MeshStandardMaterial;if(m.emissive)m.emissive.setHex(0x3c240e)}})}}
 private findData(){return this.data.find(x=>x.id===this.selected?.userData.itemId)} private modify(n:number){const d=this.findData();if(!d||!this.selected)return;this.checkpoint();d.rot+=n;this.selected.rotation.y=d.rot;this.changed()}
 private recolor(){const d=this.findData();if(!d||!this.selected)return;this.checkpoint();d.color=PALETTE[(PALETTE.indexOf(d.color)+1)%PALETTE.length];this.rebuild();this.changed()}
 private duplicate(){const d=this.findData();if(!d)return;const c=CATALOG.find(x=>x.kind===d.kind)!;this.add(c,{...d,id:crypto.randomUUID(),x:d.x+.6,z:d.z+.5})}
 private remove(){const d=this.findData();if(!d||!this.selected)return;this.checkpoint();this.scene.remove(this.selected);this.items.delete(d.id);this.data=this.data.filter(x=>x.id!==d.id);this.select(undefined);this.audio('remove');this.changed()}
 private checkpoint(){this.history.push(structuredClone(this.data));if(this.history.length>30)this.history.shift();this.future=[];this.updateButtons()} private undo(){const s=this.history.pop();if(!s)return;this.future.push(structuredClone(this.data));this.data=s;this.rebuild();this.changed()} private redo(){const s=this.future.pop();if(!s)return;this.history.push(structuredClone(this.data));this.data=s;this.rebuild();this.changed()}
 private rebuild(){this.select(undefined);this.items.forEach(g=>this.scene.remove(g));this.items.clear();for(const d of this.data){const g=this.makeItem(d);this.items.set(d.id,g);this.scene.add(g)}this.updateButtons()}
 private updateButtons(){(document.querySelector('#undo') as HTMLButtonElement).disabled=!this.history.length;(document.querySelector('#redo') as HTMLButtonElement).disabled=!this.future.length}
 private changed(){clearTimeout(this.saveTimer);this.saveTimer=window.setTimeout(()=>{localStorage.setItem('my-little-room-v1',JSON.stringify(this.data));const t=document.querySelector('#toast')!;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)},450);const p=document.querySelector('#prompt')!;p.textContent=this.data.length<3?`Add ${3-this.data.length} little thing${3-this.data.length===1?'':'s'} that feel like home.`:'Lovely. This room is becoming yours.';this.publish();this.updateButtons()}
 private load(){try{const saved=JSON.parse(localStorage.getItem('my-little-room-v1')||'null') as ItemData[]|null;if(saved?.length){this.data=saved;this.rebuild();return}}catch{};const starters=[['bed',-3.8,-2.4],['lamp',-5,-3.8],['desk',3.7,-3.8],['plant',4.8,-4.1],['teddy',-1.2,2.2],['books',2,2.7]] as const;for(const [kind,x,z] of starters){const c=CATALOG.find(q=>q.kind===kind)!;this.add(c,{x,z},false)}this.history=[];this.updateButtons()}
 private toggleTime(){this.evening=!this.evening;(this.scene.background as THREE.Color).setHex(this.evening?0x313747:0x9fa9a1);(this.scene.fog as THREE.Fog).color.setHex(this.evening?0x42404a:0xb9b4a5);if(this.keyLight)this.keyLight.intensity=this.evening?42:80;if(this.lampLight)this.lampLight.intensity=this.evening?14:5;(document.querySelector('#time-toggle')!).textContent=this.evening?'☾ Evening':'☀ Afternoon';this.audio('chime')}
 private resetCamera(){this.camera.position.set(12,10,15);this.controls.target.set(0,2.3,0);this.controls.update()}
 private audio(type:string){const A=window.AudioContext||(window as any).webkitAudioContext;if(!A)return;const ctx=new A();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=type==='remove'?190:type==='place'?420:620;g.gain.setValueAtTime(.0001,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.045,ctx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.32);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.35)}
 private update(_d:number,e:number){resizeRenderer(this.renderer,this.camera,matchMedia('(pointer:coarse)').matches?1.35:1.7);this.controls.update();if(this.dust){this.dust.rotation.y=e*.015;this.dust.position.y=Math.sin(e*.2)*.04}this.items.forEach(g=>{g.traverse(o=>{if(o.userData.glow)o.scale.setScalar(1+Math.sin(e*2)*.06)})});this.publish()}
 private publish(){const info=this.renderer.info.render;window.__THREE_GAME_DIAGNOSTICS__={frame:(window.__THREE_GAME_DIAGNOSTICS__?.frame||0)+1,fps:0,frameTimeMs:0,state:this.selected?'editing':'decorating',player:{position:{x:this.selected?.position.x||0,y:0,z:this.selected?.position.z||0}},entities:{pickups:this.data.length,total:this.data.length+1},renderer:{calls:info.calls,triangles:info.triangles,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures}}}
}
